DROP SEQUENCE IF EXISTS  s;
DROP SEQUENCE IF EXISTS s2;
DROP SEQUENCE IF EXISTS s3;

CREATE SEQUENCE IF NOT EXISTS s START WITH 100 INCREMENT BY 10;
CREATE SEQUENCE IF NOT EXISTS s2 START WITH -100 INCREMENT BY -10;
CREATE SEQUENCE IF NOT EXISTS s3 START WITH -100 INCREMENT BY 10 MINVALUE=-100 MAXVALUE=1000;

SELECT NEXTVAL(s);
SELECT NEXTVAL(s2);
SELECT NEXTVAL(s3);